spring:
  cache:
    type: redis
    redis:
      time-to-live: 30m
      cache-null-values: false
      use-key-prefix: true
      key-prefix: "msproduct:"
      enable-statistics: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:minhaSenhaForte}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 16
          max-idle: 8
          min-idle: 2
          max-wait: 2000ms
  application:
    name: ms_category
  datasource:
    url: jdbc:postgresql://localhost:5432/ms
    username: ms_user
    password: ms123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    format_sql: true
    properties:
      hibernate:
        multi_tenancy: DISCRIMINATOR

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
    logging:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/logs

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

security:
  jwt:
    public-key: classpath:keys/publicKey.pem
    expiration-time: 3600000
    refresh-expiration-time: 604800000

server:
  port: 8082


